[package]
name = "b6-compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
nasm-codegen = { path = "nasm-codegen" }
anyhow = "1.0.71"